### PR TITLE
fix bad caching headers

### PR DESCRIPTION
**Pull request by terencehonles**
Fixes: https://forum.opendatakit.org/t/invalid-character-in-last-modified-header-tomcat8-with-odk-aggregate/9162

#### What has been done to verify that this works as intended?
Currently cherry-picking the change to the release we are using and building a new jar.

#### Why is this the best possible solution? Were any other approaches considered?
Bug fix

#### Are there any risks to merging this code? If so, what are they?
None

#### Do we need any specific form for testing your changes? If so, please attach one
No

#### Does this change require updates to documentation? If so, please file an issue at https://github.com/opendatakit/docs/issues/new and include the link below.
No

### CODE REVIEW

**Comment by terencehonles** [comment]
@ggalmazor yup, I checked for all `setHeader` calls in the project. It's working fine on our end.

**Comment by ggalmazor** [comment]
I've untagged this PR for testing since it's going to be hard for @kkrawczyk123 to reproduce in the first place, and the changes are very contained.

**Comment by terencehonles** [comment]
@ggalmazor did you want me to backport this to 1.x and submit another PR? (We're running 1.x and I already have this code). Not sure how you guys are backporting features and if you have some automatic/systematic way of doing this.

**Comment by ggalmazor** [comment]
Thanks, @terencehonles! A PR sounds good.

We haven't really done any backporting yet, so we don't have a process laid out for it. I think we were thinking about creating a PR with a branch that cherry-picked the related commits.

In any case, if you've got it working, maybe we can start reviewing a PR from your branch.

**Pull request merged**
