### PR TITLE
Jr 2 10 0

### PR DESCRIPTION
**Pull request by ggalmazor**
This PR replaces #246 (I closed it and GitHub wouldn't let me reopen it after rebasing some commits)

#### What has been done to verify that this works as intended?
- I have compiled and launched Aggregate on Tomcat and GAE.
- I have uploaded a form with two fields with `odk:length` attributes and tested that answers where being truncated at the correct sizes.
    This is the form I've used: [basic_odk_length.txt](https://github.com/opendatakit/aggregate/files/2042462/basic_odk_length.txt)
- To test that form change detection worked, I uploaded the form with one field first, and then I uploaded the complete form having changed the version.

#### Why is this the best possible solution? Were any other approaches considered?
The original implementation used extension of JR artifacts that now are private and can't be extended.

This PR replaces that with some post-processing of the form after being parsed:
- Read any `odk:length` attribute on bindings to correctly size storage fields
- Store original bindings to be able to compare form changes

#### Are there any risks to merging this code? If so, what are they?
Nope.

#### Do we need any specific form for testing your changes? If so, please attach one
Nope.

#### Does this change require updates to documentation? If so, please file an issue at https://github.com/opendatakit/docs/issues/new and include the link below.
Nope.

### CODE REVIEW

**Comment by ggalmazor** [comment]
Also tested the installer, updating an existing app and installing it for the first time.

**Comment by kkrawczyk123** [comment]
I tried to load the attached form to tomcat and GAE instances of the newest master and on the local instance I can see an error:
Type Exception Report

Message org.kxml2.kdom.Document cannot be cast to org.kxml2.kdom.Element

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

java.lang.ClassCastException: org.kxml2.kdom.Document cannot be cast to org.kxml2.kdom.Element
	org.opendatakit.aggregate.parser.BaseFormParserForJavaRosa.getNodeset(BaseFormParserForJavaRosa.java:670)
	org.opendatakit.aggregate.parser.BaseFormParserForJavaRosa.lambda$storeLengthOfBinding$0(BaseFormParserForJavaRosa.java:600)
	java.util.Optional.ifPresent(Optional.java:159)
	org.opendatakit.aggregate.parser.BaseFormParserForJavaRosa.storeLengthOfBinding(BaseFormParserForJavaRosa.java:600)
	java.util.ArrayList.forEach(ArrayList.java:1257)
	org.opendatakit.aggregate.parser.BaseFormParserForJavaRosa.<init>(BaseFormParserForJavaRosa.java:418)
	org.opendatakit.aggregate.parser.FormParserForJavaRosa.<init>(FormParserForJavaRosa.java:114)
	org.opendatakit.aggregate.servlet.FormUploadServlet.doPost(FormUploadServlet.java:255)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
	org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	org.opendatakit.common.security.spring.SecurityContextHolderAwareAuthPreservingRequestFilter.doFilter(SecurityContextHolderAwareAuthPreservingRequestFilter.java:66)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	org.opendatakit.common.security.spring.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:84)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	org.opendatakit.common.security.spring.OutOfBandUserFilter.doFilter(OutOfBandUserFilter.java:105)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	org.opendatakit.common.security.spring.Oauth2ResourceFilter.doFilter(Oauth2ResourceFilter.java:352)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	org.springframework.security.web.access.channel.ChannelProcessingFilter.doFilter(ChannelProcessingFilter.java:157)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
Note The full stack trace of the root cause is available in the server logs.

and on GAE instance:
screenshot from 2018-06-25 14-25-22


I am able to load that form on 1.5 gae instance. Is that some kind of regression ?? Should I report a separate issue for that?

**Comment by lognaturel** [comment]
@kkrawczyk123 could you please try the same on https://github.com/opendatakit/aggregate/pull/256? I wonder if it was related to that issue.

**Comment by kkrawczyk123** [comment]
@lognaturel I am not sure if those issues are related as I am able to update forms version and preview a new version of the form - no errors are visible but according to basic_odk_length form I am able to add it to aggregate only when I remove "odk:length" option.

**Pull request merged**
