### PR TITLE
New feature that lets a user see Audit CSV contents inside a popup in Aggregate's submissions table

### PR DESCRIPTION
**Pull request by ggalmazor**
This PR solves #102 

It covers just a basic feature to enable users to see Audit CSV contents inside a simple popup. 

Some UI improvements that could be addressed:
 - New button image (currently using preview button image)
 - Some styling or HTML structuring to the Audit CSV data (maybe formatting it into a table)

Some code improvements that could also be addressed:
 - Reduce duplication of code in `SubmissionServiceImpl` and `BinaryDataServlet`

### CODE REVIEW

**Comment by lognaturel** [comment]
Verified with both `orx:audit` (most strictly correct) and `audit` (acceptable). Also verified that Briefcase pulls down the audit csv.

Line breaks don't seem to be respected so it's really hard to read! I think it's worth putting into a table now so it's more usable. I'm also surprised to see that the text can be selected but not copied. It would be useful for it to be able to be copied.

**Comment by ggalmazor** [comment]
> "the text can be selected but not copied"
That's some GWT black magic there :/ I'll look into that!

**Comment by ggalmazor** [comment]
@lognaturel could we merge this one and wait for #112 to be merged before improving the Audit CSV popup? Fixing this on master would require me to set up the old Eclipse dev environment and I could go faster on the new Gradle project...

**Comment by lognaturel** [comment]
Merged, @ggalmazor! That does make more sense.

**Pull request merged**
