### PR TITLE
Issue 210 validate publisher form

### LINKED ISSUE #208: User is asked for email address when publishing submissions/forms to servers.
#### Software and hardware versions 
Aggregate v1.4.x, Java v1.8.x, ...

#### Problem description
The user is asked for his "email address that will be granted access to these documents" when he is publishing data to JSON server,  Ohmage JSON Server and REDCap Server - but what documents? 

#### Steps to reproduce the problem
Click on publish button next to  submission or form and choose one of the servers and click on publish on the displayed window - you don't have to choose any url to test it (which is the other issue that I will report)

#### Expected behavior
User should be asked for email address only when he is publishing to Google Spreadsheet and Google Fusion Tables - here gaining access to documents does make a sense. 

#### Other information 
Screenshot with an example attached:
screenshot_exportred

### LINKED ISSUE #210: Too late error message when not choosing name workbook name when publishing to Google Spreadsheet.
#### Software and hardware versions 
Aggregate v1.4.x, Java v1.8.x, ...

#### Problem description
Too late error message when not choosing name workbook name when publishing to Google Spreadsheet.

#### Steps to reproduce the problem
Click on publish button next to submission or form. Choose to publish to Google Spreadsheet. Leave Workbook name field empty. Click on publish button. Dialog message asking you for email will appear. Input email address, confirm email address and finally, you will see error message informing you that "Spreadsheet name must be supplied."

#### Expected behavior
Error message shows which is good but it should display earlier or give users the chance to correct his action and input workbook name again or publish button may be disabled when user doesn't choose a workbook name.

#### Other information 
Screenshot of error message attached.
screenshot_error spreadsheet

### PR DESCRIPTION
**Pull request by ggalmazor**
Closes #208, #209, #210

#### What has been done to verify that this works as intended?
Manually tried all field combinations in both publishers in the dev server.

#### Why is this the best possible solution? Were any other approaches considered?
No other approaches were considered. It's the narrowest change I could come up with that provides basic form validation.

An alternative would be to disable the button if the form is not valid. I don't have a strong opinion about this approach.

#### Are there any risks to merging this code? If so, what are they?

Common publisher form changes:
- Alerts will be shown when no type of publisher or kind of upload (all, new, existing) is selected
  There is really no way to test this without tampering with the form, although validating forms is always a good idea. These validations will be handy in case we change the form and we open the option of not selecting an option on those selects.

Changes to the Google Spreasheet publisher form:
- Users should expect a new publisher form that includes the owner's email:
  image
- Alerts will be shown if the user doesn't provide a workbook name or a valid owner's email address.

Changes to the JSON publisher form:
- It won't ask for the owner's email, since it's not really required to create it.
- In the publishers table, we use "N/A" in the "owner" column for JSON publishers.

#### Do we need any specific form for testing your changes? If so, please attach one
Nope.

#### Does this change require updates to documentation? If so, please file an issue at https://github.com/opendatakit/docs/issues/new and include the link below.
No.

### CODE REVIEW

**Comment by kkrawczyk123** [comment]
@ggalmazor Validation on Google Spreadsheet works great! But I have noticed some issues:
- when I input email address I did not receive the email with access to sheet and in the published data tab emails are cut off, screenshot attached: 
screenshot from 2019-03-05 10-15-25

- Publish to JSON server is still allowed without input to any field on the dialog window. I think that URL field should be required one. 

@opendatakit-bot unlabel "needs testing"

**Comment by ggalmazor** [comment]
Thanks, @kkrawczyk123!

I've added a couple of commits:
- One that fixes the issue with the cropped email addresses
- One that adds validation to the json publisher form (only checks the url field, and ensures that it's actually a URL)

**Comment by ggalmazor** [comment]
I've left out url validation form the json publisher changes because it's more controversial than I thought it was going to be. There is no consensus on how a url should be validated in javascript (can't use Java for this one), and we will have to implement a custom regexp that meets all our needs: require http or https, support localhost, port numbers and simple paths.

In any case, if a user enters an invalid url, the publisher will fail and they will get feedback to make amends, therefore, I think it's safe to release this and improve it in a next release.

**Comment by kkrawczyk123** [comment]
**Tested with success!**
Confirmed that issues have been fixed.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Pull request merged**
